INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (1, null, 'Women\'s Fashion');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (2, null, 'Men\'s Fashion');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (3, null, 'Electronics');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (4, null, 'Home & Lifestyle');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (5, null, 'Medicine');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (6, null, 'Sports & Outdoor');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (7, null, 'Toy');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (8, null, 'Pet');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (9, 1, 'Skirt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (10, 1, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (11, 1, 'Trousers');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (12, 1, 'Coat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (13, 1, 'Shoes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (14, 1, 'Underwear');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (15, 1, 'Accessory');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (16, 9, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (17, 9, 'Sun Protection');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (18, 9, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (19, 10, 'T-Shirt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (20, 10, 'Blouse');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (21, 10, 'Dress');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (22, 11, 'Kaki');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (23, 11, 'Jean');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (24, 11, 'Short');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (25, 12, 'Vest');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (26, 12, 'Jean');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (27, 12, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (28, 13, 'Sandals');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (29, 13, 'High heels');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (30, 13, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (31, 14, 'Bra');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (32, 14, 'Body suit');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (33, 14, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (34, 15, 'Hand bag');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (35, 15, 'Belt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (36, 15, 'Wallet');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (38, 2, 'Hat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (39, 2, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (40, 2, 'Trousers');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (41, 2, 'Coat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (42, 2, 'Shoes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (43, 2, 'Underwear');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (44, 2, 'Accessory');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (45, 38, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (46, 38, 'Cap');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (47, 38, 'Fedora');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (48, 39, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (49, 39, 'T-Shirt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (50, 39, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (51, 40, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (52, 40, 'Short');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (53, 40, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (54, 41, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (55, 41, 'Vest');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (56, 41, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (57, 42, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (58, 42, 'Sneaker');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (59, 42, 'Bata');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (60, 43, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (61, 43, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (62, 44, 'Belt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (63, 44, 'Watch');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (64, 44, 'Wallet');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (65, 3, 'Electrical appliances');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (66, 3, 'Household appliances');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (67, 3, 'Telecommunications');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (68, 3, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (69, 65, 'Television');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (70, 65, 'Fridge');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (71, 65, 'Washing Machine');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (72, 65, 'Air Conditioner');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (73, 66, 'Electric Cooker');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (74, 66, 'Vacuum Cleaner');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (75, 66, 'Electric Stove');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (76, 66, 'Water Filter');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (77, 67, 'Smart Phone');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (78, 67, 'Laptop');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (79, 67, 'Pc Computer');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (80, 67, 'Tablet');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (81, 4, 'Living Room');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (82, 4, 'Bedroom');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (83, 4, 'Kitchen');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (84, 4, 'Bathroom');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (85, 4, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (86, 81, 'Sofa');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (87, 81, 'Shelves');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (88, 81, 'Tea Table');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (89, 81, 'Mat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (90, 82, 'Drap');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (91, 82, 'Pillow');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (92, 82, 'Blanket');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (93, 82, 'Mattress');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (94, 84, 'Soap and Gel');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (95, 84, 'Teeth');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (96, 84, 'Towel');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (97, 84, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (98, 5, 'Medication');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (99, 5, 'Nutrition');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (100, 5, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (101, 98, 'Bones and Joints');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (102, 98, 'Cough');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (103, 98, 'Painkiller');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (104, 98, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (105, 99, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (106, 99, 'Oil');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (107, 99, 'Milk');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (108, 6, 'Ball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (109, 6, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (110, 6, 'Accessory');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (111, 6, 'Shoes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (112, 6, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (113, 108, 'Football');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (114, 108, 'Volleyball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (115, 108, 'Basketball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (116, 108, 'Tennis');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (117, 109, 'Football');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (118, 109, 'Volleyball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (119, 109, 'Basketball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (120, 109, 'Tennis');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (121, 110, 'Football');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (122, 110, 'Volleyball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (123, 110, 'Basketball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (124, 110, 'Tennis');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (125, 111, 'Football');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (126, 111, 'Volleyball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (127, 111, 'Basketball');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (128, 111, 'Tennis');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (129, 7, 'Newborn');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (130, 7, 'From 1 to 3 ages');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (131, 7, 'From 4 to 6 ages');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (132, 7, 'Over 6 ages');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (133, 130, 'Building');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (134, 130, 'Simulation');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (135, 130, 'Education');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (136, 131, 'Building');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (137, 131, 'Simulation');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (138, 131, 'Education');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (139, 132, 'Building');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (140, 132, 'Simulation');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (141, 132, 'Education');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (142, 8, 'Dog');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (143, 8, 'Cat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (144, 8, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (145, 142, 'Food');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (146, 142, 'Milk');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (147, 142, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (148, 142, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (149, 143, 'Food');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (150, 143, 'Milk');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (151, 143, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (152, 143, 'Others');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (153, 83, 'Pot');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (154, 83, 'Utensil');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (155, 83, 'Cooking tools');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (156, 83, 'Others');
