INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (1, null, 'Women\'s Fashion');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (2, null, 'Men\'s Fashion');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (3, null, 'Electronics');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (4, null, 'Home & Lifestyle');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (5, null, 'Medicine');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (6, null, 'Sports & Outdoor');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (7, null, 'Baby\'s and Toys');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (8, null, 'Groceries & Pets');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (9, 1, 'Skirt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (10, 1, 'Clothes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (11, 1, 'Trousers');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (12, 1, 'Coat');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (13, 1, 'Shoes');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (14, 1, 'Underwear');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (15, 1, 'Accessory');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (16, 9, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (17, 9, 'Sun Protection');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (18, 9, 'Modern');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (19, 10, 'T-Shirt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (20, 10, 'Blouse');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (21, 10, 'Dress');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (22, 11, 'Kaki');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (23, 11, 'Jean');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (24, 11, 'Short');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (25, 12, 'Vest');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (26, 12, 'Jean');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (27, 12, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (28, 13, 'Sandals');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (29, 13, 'High heels');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (30, 13, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (31, 14, 'Bra');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (32, 14, 'Body suit');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (33, 14, 'Normal');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (34, 15, 'Hand bag');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (35, 15, 'Belt');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (36, 15, 'Wallet');
INSERT INTO ecommerce_shop.product_type (product_type_id, parent_id, type_product) VALUES (37, 15, 'HAND BAG');
