spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce_shop
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    tính năng open-in-view được bật theo mặc định.
#  Điều này có thể gây ra các truy vấn cơ sở dữ liệu không cần thiết trong quá trình render view,
#  ảnh hưởng đến hiệu suất và khả năng quản lý giao dịch.
    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect